;;; jira-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from jira.el

(register-definition-prefixes "jira" '("jira-version"))


;;; Generated autoloads from jira-actions.el

(register-definition-prefixes "jira-actions" '("jira-actions-"))


;;; Generated autoloads from jira-api.el

(register-definition-prefixes "jira-api" '("jira-"))


;;; Generated autoloads from jira-detail.el

(register-definition-prefixes "jira-detail" '("jira-detail-"))


;;; Generated autoloads from jira-doc.el

(register-definition-prefixes "jira-doc" '("jira-doc-"))


;;; Generated autoloads from jira-fmt.el

(register-definition-prefixes "jira-fmt" '("jira-"))


;;; Generated autoloads from jira-issues.el

 (autoload 'jira-issues "jira-issues" nil t)
(register-definition-prefixes "jira-issues" '("jira-issues-"))


;;; Generated autoloads from jira-table.el

(register-definition-prefixes "jira-table" '("jira-table-"))


;;; Generated autoloads from jira-tempo.el

 (autoload 'jira-tempo "jira-tempo" nil t)
(register-definition-prefixes "jira-tempo" '("jira-tempo-"))


;;; Generated autoloads from jira-utils.el

(register-definition-prefixes "jira-utils" '("jira-"))

;;; End of scraped data

(provide 'jira-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jira-autoloads.el ends here
