;;; thirdstream-theme.el --- Theme Thirdstream

;; Copyright (C) 2020 Daw-Ran Liou

;; Author: Daw-Ran Liou
;; Version: 0.1
;; Package-Requires: ((emacs "24"))
;; Created with ThemeCreator, https://github.com/mswift42/themecreator.


;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program. If not, see <http://www.gnu.org/licenses/>.

;; This file is not part of Emacs.

;;; Commentary:

;;; Code:

 (deftheme thirdstream)
 (let ((class '((class color) (min-colors 89)))
       (fg "#111111")
       (bg "#ffffff")
       (highlight-gray "#d6d6d6")
       (highlight-light-yellow "#fffceb")
       (highlight-yellow "#fbf1a9")
       (highlight-green "#9eebcf")
       (highlight-blue "#cdecff")
       (highlight-red "#ff725c")
       (builtin "#111111")
       (keyword "#111111")
       (const   "#111111")
       (comment "#bbbbbb")
       (func    "#111111")
       (str     "#111111")
       (type    "#111111")
       (var     "#111111")
       (warning "#ff0000")
       (warning2 "#ff8800"))
   (custom-theme-set-faces
   'thirdstream
        `(default ((,class (:background ,bg :foreground ,fg))))
        `(font-lock-builtin-face ((,class (:foreground ,builtin))))
        `(font-lock-comment-face ((,class (:foreground ,comment))))
	`(font-lock-negation-char-face ((,class (:foreground ,const))))
	`(font-lock-reference-face ((,class (:foreground ,const))))
	`(font-lock-constant-face ((,class (:foreground ,const))))
        `(font-lock-doc-face ((,class (:foreground ,comment))))
        `(font-lock-function-name-face ((,class (:foreground ,func ))))
        `(font-lock-keyword-face ((,class (:foreground ,keyword))))
        `(font-lock-string-face ((,class (:foreground ,str :background ,highlight-blue))))
        `(font-lock-type-face ((,class (:foreground ,type ))))
        `(font-lock-variable-name-face ((,class (:foreground ,var))))
        `(font-lock-warning-face ((,class (:foreground ,warning :background ,highlight-gray))))
        `(term-color-black ((,class (:foreground ,fg :background nil))))
        `(region ((,class (:foreground ,fg :background ,highlight-yellow))))
        `(highlight ((,class (:foreground ,fg :background ,highlight-yellow))))
        `(idle-highlight ((,class (:foreground ,fg :background ,highlight-gray))))
	`(hl-line ((,class (:background  ,highlight-gray))))
	`(fringe ((,class (:background ,bg :foreground ,comment))))
	`(cursor ((,class (:background ,fg :foreground ,bg))))
        `(show-paren-match ((,class (:background ,highlight-yellow :bold t))))
        `(isearch ((,class (:bold t :foreground ,warning :background ,highlight-gray))))
        `(mode-line ((,class (:box (:line-width 1 :color nil) :bold t :foreground ,fg :background ,highlight-gray))))
        `(mode-line-inactive ((,class (:box (:line-width 1 :color nil :style pressed-button) :foreground ,var :background ,bg :weight normal))))
        `(mode-line-buffer-id ((,class (:bold t :foreground ,func :background nil))))
	`(mode-line-highlight ((,class (:foreground ,keyword :box nil :weight bold))))
        `(mode-line-emphasis ((,class (:foreground ,fg))))
	`(vertical-border ((,class (:foreground ,fg))))
        `(minibuffer-prompt ((,class (:bold t :foreground ,keyword))))
        `(default-italic ((,class (:italic t))))
	`(link ((,class (:foreground ,const :underline t))))
	`(org-code ((,class (:foreground ,fg))))
	`(org-hide ((,class (:foreground ,fg))))
        `(org-level-1 ((,class (:bold t :foreground ,fg :height 1.1))))
        `(org-level-2 ((,class (:bold nil :foreground ,fg))))
        `(org-level-3 ((,class (:bold t :foreground ,fg))))
        `(org-level-4 ((,class (:bold nil :foreground ,highlight-gray))))
        `(org-date ((,class (:underline t :foreground ,var) )))
        `(org-footnote  ((,class (:underline t :foreground ,fg))))
        `(org-link ((,class (:underline t :foreground ,type ))))
        `(org-special-keyword ((,class (:foreground ,func))))
        `(org-block ((,class (:foreground ,fg))))
        `(org-quote ((,class (:inherit org-block :slant italic))))
        `(org-verse ((,class (:inherit org-block :slant italic))))
        `(org-todo ((,class (:box (:line-width 1 :color ,fg) :foreground ,keyword :bold t))))
        `(org-done ((,class (:box (:line-width 1 :color ,highlight-gray) :bold t :foreground ,highlight-gray))))
        `(org-warning ((,class (:underline t :foreground ,warning))))
        `(org-agenda-structure ((,class (:weight bold :foreground ,fg :box (:color ,fg) :background ,highlight-gray))))
        `(org-agenda-date ((,class (:foreground ,var :height 1.1 ))))
        `(org-agenda-date-weekend ((,class (:weight normal :foreground ,fg))))
        `(org-agenda-date-today ((,class (:weight bold :foreground ,keyword :height 1.4))))
        `(org-agenda-done ((,class (:foreground ,highlight-gray))))
	`(org-scheduled ((,class (:foreground ,type))))
        `(org-scheduled-today ((,class (:foreground ,func :weight bold :height 1.2))))
	`(org-ellipsis ((,class (:foreground ,builtin))))
	`(org-verbatim ((,class (:foreground ,fg))))
        `(org-document-info-keyword ((,class (:foreground ,func))))
	`(font-latex-bold-face ((,class (:foreground ,type))))
	`(font-latex-italic-face ((,class (:foreground ,var :italic t))))
	`(font-latex-string-face ((,class (:foreground ,str))))
	`(font-latex-match-reference-keywords ((,class (:foreground ,const))))
	`(font-latex-match-variable-keywords ((,class (:foreground ,var))))
	`(ido-only-match ((,class (:foreground ,warning))))
	`(org-sexp-date ((,class (:foreground ,fg))))
	`(ido-first-match ((,class (:foreground ,keyword :bold t))))
        `(ivy-current-match ((,class (:foreground ,fg :inherit highlight :underline t))))
	`(gnus-header-content ((,class (:foreground ,keyword))))
	`(gnus-header-from ((,class (:foreground ,var))))
	`(gnus-header-name ((,class (:foreground ,type))))
	`(gnus-header-subject ((,class (:foreground ,func :bold t))))
	`(mu4e-view-url-number-face ((,class (:foreground ,type))))
	`(mu4e-cited-1-face ((,class (:foreground ,fg))))
	`(mu4e-cited-7-face ((,class (:foreground ,fg))))
	`(mu4e-header-marks-face ((,class (:foreground ,type))))
	`(ffap ((,class (:foreground ,fg))))
	`(js2-private-function-call ((,class (:foreground ,const))))
	`(js2-jsdoc-html-tag-delimiter ((,class (:foreground ,str))))
	`(js2-jsdoc-html-tag-name ((,class (:foreground ,var))))
	`(js2-external-variable ((,class (:foreground ,type  ))))
        `(js2-function-param ((,class (:foreground ,const))))
        `(js2-jsdoc-value ((,class (:foreground ,str))))
        `(js2-private-member ((,class (:foreground ,fg))))
        `(js3-warning-face ((,class (:underline ,keyword))))
        `(js3-error-face ((,class (:underline ,warning))))
        `(js3-external-variable-face ((,class (:foreground ,var))))
        `(js3-function-param-face ((,class (:foreground ,fg))))
        `(js3-jsdoc-tag-face ((,class (:foreground ,keyword))))
        `(js3-instance-member-face ((,class (:foreground ,const))))
	`(warning ((,class (:foreground ,warning))))
	`(ac-completion-face ((,class (:underline t :foreground ,keyword))))
	`(info-quoted-name ((,class (:foreground ,builtin))))
	`(info-string ((,class (:foreground ,str))))
	`(icompletep-determined ((,class :foreground ,builtin)))
        `(undo-tree-visualizer-current-face ((,class :foreground ,builtin)))
        `(undo-tree-visualizer-default-face ((,class :foreground ,fg)))
        `(undo-tree-visualizer-unmodified-face ((,class :foreground ,var)))
        `(undo-tree-visualizer-register-face ((,class :foreground ,type)))
	`(slime-repl-inputed-output-face ((,class (:foreground ,type))))
        `(trailing-whitespace ((,class :foreground nil :background ,warning)))
        `(rainbow-delimiters-depth-1-face ((,class :foreground ,fg)))
        `(rainbow-delimiters-depth-2-face ((,class :foreground ,type)))
        `(rainbow-delimiters-depth-3-face ((,class :foreground ,var)))
        `(rainbow-delimiters-depth-4-face ((,class :foreground ,const)))
        `(rainbow-delimiters-depth-5-face ((,class :foreground ,keyword)))
        `(rainbow-delimiters-depth-6-face ((,class :foreground ,fg)))
        `(rainbow-delimiters-depth-7-face ((,class :foreground ,type)))
        `(rainbow-delimiters-depth-8-face ((,class :foreground ,var)))
        `(magit-item-highlight ((,class :background ,highlight-gray)))
        `(magit-section-heading        ((,class (:foreground ,keyword :weight bold))))
        `(magit-hunk-heading           ((,class (:background ,highlight-gray))))
        `(magit-section-highlight      ((,class (:background ,highlight-gray))))
        `(magit-hunk-heading-highlight ((,class (:background ,highlight-gray))))
        `(magit-diff-context-highlight ((,class (:background ,highlight-gray :foreground ,fg))))
        `(magit-diffstat-added   ((,class (:foreground ,type))))
        `(magit-diffstat-removed ((,class (:foreground ,var))))
        `(magit-process-ok ((,class (:foreground ,func :weight bold))))
        `(magit-process-ng ((,class (:foreground ,warning :weight bold))))
        `(magit-branch ((,class (:foreground ,const :weight bold))))
        `(magit-log-author ((,class (:foreground ,fg))))
        `(magit-hash ((,class (:foreground ,fg))))
        `(magit-diff-file-header ((,class (:foreground ,fg :background ,highlight-gray))))
        `(lazy-highlight ((,class (:foreground ,fg :background ,highlight-gray))))
        `(term ((,class (:foreground ,fg :background ,bg))))
        `(term-color-black ((,class (:foreground ,highlight-gray :background ,highlight-gray))))
        `(term-color-blue ((,class (:foreground ,func :background ,func))))
        `(term-color-red ((,class (:foreground ,keyword :background ,highlight-gray))))
        `(term-color-green ((,class (:foreground ,type :background ,highlight-gray))))
        `(term-color-yellow ((,class (:foreground ,var :background ,var))))
        `(term-color-magenta ((,class (:foreground ,builtin :background ,builtin))))
        `(term-color-cyan ((,class (:foreground ,str :background ,str))))
        `(term-color-white ((,class (:foreground ,fg :background ,fg))))
        `(rainbow-delimiters-unmatched-face ((,class :foreground ,warning)))
        `(helm-header ((,class (:foreground ,fg :background ,bg :underline nil :box nil))))
        `(helm-source-header ((,class (:foreground ,keyword :background ,bg :underline nil :weight bold))))
        `(helm-selection ((,class (:background ,highlight-gray :underline nil))))
        `(helm-selection-line ((,class (:background ,highlight-gray))))
        `(helm-visible-mark ((,class (:foreground ,bg :background ,highlight-gray))))
        `(helm-candidate-number ((,class (:foreground ,bg :background ,fg))))
        `(helm-separator ((,class (:foreground ,type :background ,bg))))
        `(helm-time-zone-current ((,class (:foreground ,builtin :background ,bg))))
        `(helm-time-zone-home ((,class (:foreground ,type :background ,bg))))
        `(helm-buffer-not-saved ((,class (:foreground ,type :background ,bg))))
        `(helm-buffer-process ((,class (:foreground ,builtin :background ,bg))))
        `(helm-buffer-saved-out ((,class (:foreground ,fg :background ,bg))))
        `(helm-buffer-size ((,class (:foreground ,fg :background ,bg))))
        `(helm-ff-directory ((,class (:foreground ,func :background ,bg :weight bold))))
        `(helm-ff-file ((,class (:foreground ,fg :background ,bg :weight normal))))
        `(helm-ff-executable ((,class (:foreground ,var :background ,bg :weight normal))))
        `(helm-ff-invalid-symlink ((,class (:foreground ,warning2 :background ,bg :weight bold))))
        `(helm-ff-symlink ((,class (:foreground ,keyword :background ,bg :weight bold))))
        `(helm-ff-prefix ((,class (:foreground ,bg :background ,keyword :weight normal))))
        `(helm-grep-cmd-line ((,class (:foreground ,fg :background ,bg))))
        `(helm-grep-file ((,class (:foreground ,fg :background ,bg))))
        `(helm-grep-finish ((,class (:foreground ,fg :background ,bg))))
        `(helm-grep-lineno ((,class (:foreground ,fg :background ,bg))))
        `(helm-grep-match ((,class (:foreground nil :background nil :inherit helm-match))))
        `(helm-grep-running ((,class (:foreground ,func :background ,bg))))
        `(helm-moccur-buffer ((,class (:foreground ,func :background ,bg))))
        `(helm-source-go-package-godoc-description ((,class (:foreground ,str))))
        `(helm-bookmark-w3m ((,class (:foreground ,type))))
        `(company-echo-common ((,class (:foreground ,bg :background ,fg))))
        `(company-preview ((,class (:background ,highlight-gray :foreground ,var))))
        `(company-preview-common ((,class (:foreground ,highlight-gray :foreground ,fg))))
        `(company-preview-search ((,class (:foreground ,type :background ,bg))))
        `(company-scrollbar-bg ((,class (:background ,highlight-gray))))
        `(company-scrollbar-fg ((,class (:foreground ,keyword))))
        `(company-tooltip ((,class (:foreground ,fg :background ,highlight-gray :bold t))))
        `(company-tooltop-annotation ((,class (:foreground ,const))))
        `(company-tooltip-common ((,class ( :foreground ,fg))))
        `(company-tooltip-common-selection ((,class (:foreground ,str))))
        `(company-tooltip-mouse ((,class (:inherit highlight))))
        `(company-tooltip-selection ((,class (:background ,highlight-yellow :foreground ,fg))))
        `(company-template-field ((,class (:inherit region))))
        `(web-mode-builtin-face ((,class (:inherit ,font-lock-builtin-face))))
        `(web-mode-comment-face ((,class (:inherit ,font-lock-comment-face))))
        `(web-mode-constant-face ((,class (:inherit ,font-lock-constant-face))))
        `(web-mode-keyword-face ((,class (:foreground ,keyword))))
        `(web-mode-doctype-face ((,class (:inherit ,font-lock-comment-face))))
        `(web-mode-function-name-face ((,class (:inherit ,font-lock-function-name-face))))
        `(web-mode-string-face ((,class (:foreground ,str))))
        `(web-mode-type-face ((,class (:inherit ,font-lock-type-face))))
        `(web-mode-html-attr-name-face ((,class (:foreground ,func))))
        `(web-mode-html-attr-value-face ((,class (:foreground ,keyword))))
        `(web-mode-warning-face ((,class (:inherit ,font-lock-warning-face))))
        `(web-mode-html-tag-face ((,class (:foreground ,builtin))))
        `(jde-java-font-lock-package-face ((t (:foreground ,var))))
        `(jde-java-font-lock-public-face ((t (:foreground ,keyword))))
        `(jde-java-font-lock-private-face ((t (:foreground ,keyword))))
        `(jde-java-font-lock-constant-face ((t (:foreground ,const))))
        `(jde-java-font-lock-modifier-face ((t (:foreground ,fg))))
        `(jde-jave-font-lock-protected-face ((t (:foreground ,keyword))))
        `(jde-java-font-lock-number-face ((t (:foreground ,var))))))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'thirdstream)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; thirdstream-theme.el ends here
