;;; gotest-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gotest.el

(autoload 'go-test-current-test-cache "gotest" "\
Repeat the previous current test execution." t)
(autoload 'go-test-current-test "gotest" "\
Launch go test on the current test.

(fn &optional LAST)" t)
(autoload 'go-test-current-file "gotest" "\
Launch go test on the current buffer file." t)
(autoload 'go-test-current-project "gotest" "\
Launch go test on the current project." t)
(autoload 'go-test-current-benchmark "gotest" "\
Launch go benchmark on current benchmark." t)
(autoload 'go-test-current-file-benchmarks "gotest" "\
Launch go benchmark on current file benchmarks." t)
(autoload 'go-test-current-project-benchmarks "gotest" "\
Launch go benchmark on current project." t)
(autoload 'go-test-current-coverage "gotest" "\
Launch go test coverage on the current project." t)
(autoload 'go-run "gotest" "\
Launch go run on current buffer file.

(fn &optional ARGS)" t)
(register-definition-prefixes "gotest" '("go-"))

;;; End of scraped data

(provide 'gotest-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gotest-autoloads.el ends here
