;;; copilot-chat-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from copilot-chat.el

(register-definition-prefixes "copilot-chat" '("copilot-chat-frontend"))


;;; Generated autoloads from copilot-chat-command.el

 (autoload 'copilot-chat-ask-and-insert "copilot-chat" nil t)
 (autoload 'copilot-chat-explain "copilot-chat" nil t)
 (autoload 'copilot-chat-review "copilot-chat" nil t)
 (autoload 'copilot-chat-doc "copilot-chat" nil t)
 (autoload 'copilot-chat-fix "copilot-chat" nil t)
 (autoload 'copilot-chat-optimize "copilot-chat" nil t)
 (autoload 'copilot-chat-test "copilot-chat" nil t)
 (autoload 'copilot-chat-explain-symbol-at-line "copilot-chat" nil t)
 (autoload 'copilot-chat-explain-defun "copilot-chat" nil t)
 (autoload 'copilot-chat-custom-prompt-function "copilot-chat" nil t)
 (autoload 'copilot-chat-review-whole-buffer "copilot-chat" nil t)
 (autoload 'copilot-chat-switch-to-buffer "copilot-chat" nil t)
 (autoload 'copilot-chat-custom-prompt-selection "copilot-chat" nil t)
 (autoload 'copilot-chat-custom-prompt-mini-buffer "copilot-chat" nil t)
 (autoload 'copilot-chat-list "copilot-chat" nil t)
 (autoload 'copilot-chat-display "copilot-chat" nil t)
 (autoload 'copilot-chat-hide "copilot-chat" nil t)
 (autoload 'copilot-chat-insert-commit-message-when-ready "copilot-chat" nil t)
 (autoload 'copilot-chat-insert-commit-message "copilot-chat" nil t)
 (autoload 'copilot-chat-set-model "copilot-chat" nil t)
 (autoload 'copilot-chat-clear-auth-cache "copilot-chat" nil t)
 (autoload 'copilot-chat-reset-models "copilot-chat" nil t)
(register-definition-prefixes "copilot-chat-command" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-common.el

(register-definition-prefixes "copilot-chat-common" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-copilot.el

(register-definition-prefixes "copilot-chat-copilot" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-curl.el

(register-definition-prefixes "copilot-chat-curl" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-frontend.el

(register-definition-prefixes "copilot-chat-frontend" '("copilot-chat--"))


;;; Generated autoloads from copilot-chat-instance.el

 (autoload 'copilot-chat-kill-instance "copilot-chat" nil t)
(register-definition-prefixes "copilot-chat-instance" '("copilot-chat--"))


;;; Generated autoloads from copilot-chat-markdown.el

(register-definition-prefixes "copilot-chat-markdown" '("copilot-chat-" "poly-copilot-markdown-"))


;;; Generated autoloads from copilot-chat-org.el

(register-definition-prefixes "copilot-chat-org" '("copilot-chat-" "poly-copilot-org-"))


;;; Generated autoloads from copilot-chat-prompt-mode.el

(register-definition-prefixes "copilot-chat-prompt-mode" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-prompts.el

(register-definition-prefixes "copilot-chat-prompts" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-request.el

(register-definition-prefixes "copilot-chat-request" '("copilot-chat--"))


;;; Generated autoloads from copilot-chat-shell-maker.el

(register-definition-prefixes "copilot-chat-shell-maker" '("copilot-chat--shell"))


;;; Generated autoloads from copilot-chat-transient.el

 (autoload 'copilot-chat-transient "copilot-chat" nil t)
 (autoload 'copilot-chat-transient-buffers "copilot-chat" nil t)
 (autoload 'copilot-chat-transient-code "copilot-chat" nil t)

;;; End of scraped data

(provide 'copilot-chat-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; copilot-chat-autoloads.el ends here
