;;; esup-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from esup.el

(autoload 'esup "esup" "\
Profile the startup time of Emacs in the background.
If INIT-FILE is non-nil, profile that instead of USER-INIT-FILE.
ARGS is a list of extra command line arguments to pass to Emacs.

(fn &optional INIT-FILE &rest ARGS)" t)
(register-definition-prefixes "esup" '("esup-"))


;;; Generated autoloads from esup-child.el

(register-definition-prefixes "esup-child" '("esup-" "with-esup-child-increasing-depth"))

;;; End of scraped data

(provide 'esup-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; esup-autoloads.el ends here
