;;; janet-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from janet-mode.el

(autoload 'janet-mode "janet-mode" "\
Major mode for the Janet language

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.janet\\'" . janet-mode))
(add-to-list 'interpreter-mode-alist '("janet" . janet-mode))
(register-definition-prefixes "janet-mode" '("janet-"))

;;; End of scraped data

(provide 'janet-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; janet-mode-autoloads.el ends here
