;;; theme-loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from standard-dark-theme.el

(put 'standard-dark 'theme-properties (list :background-mode 'dark :kind 'color-scheme :family 'standard))


;;; Generated autoloads from standard-dark-tinted-theme.el

(put 'standard-dark-tinted 'theme-properties (list :background-mode 'dark :kind 'color-scheme :family 'standard))


;;; Generated autoloads from standard-light-theme.el

(put 'standard-light 'theme-properties (list :background-mode 'light :kind 'color-scheme :family 'standard))


;;; Generated autoloads from standard-light-tinted-theme.el

(put 'standard-light-tinted 'theme-properties (list :background-mode 'light :kind 'color-scheme :family 'standard))

;;; End of scraped data

(provide 'theme-loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; theme-loaddefs.el ends here
