;;; casual-dired-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from casual-dired.el

 (autoload 'casual-dired-tmenu "casual-dired" nil t)
(register-definition-prefixes "casual-dired" '("casual-dired-"))


;;; Generated autoloads from casual-dired-settings.el

(register-definition-prefixes "casual-dired-settings" '("casual-dired-"))


;;; Generated autoloads from casual-dired-sort-by.el

(register-definition-prefixes "casual-dired-sort-by" '("casual-dired--"))


;;; Generated autoloads from casual-dired-variables.el

(register-definition-prefixes "casual-dired-variables" '("casual-dired-"))


;;; Generated autoloads from casual-dired-version.el

(register-definition-prefixes "casual-dired-version" '("casual-dired-version"))

;;; End of scraped data

(provide 'casual-dired-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; casual-dired-autoloads.el ends here
