;;; kotlin-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from kotlin-mode.el

(autoload 'kotlin-mode "kotlin-mode" "\
Major mode for editing Kotlin.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.kts?\\'" . kotlin-mode) t)
(register-definition-prefixes "kotlin-mode" '("kotlin-"))


;;; Generated autoloads from kotlin-mode-indent.el

(register-definition-prefixes "kotlin-mode-indent" '("kotlin-"))


;;; Generated autoloads from kotlin-mode-lexer.el

(register-definition-prefixes "kotlin-mode-lexer" '("kotlin-mode-"))

;;; End of scraped data

(provide 'kotlin-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kotlin-mode-autoloads.el ends here
