;;; casual-lib-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from casual-lib.el

(register-definition-prefixes "casual-lib" '("casual-lib-"))


;;; Generated autoloads from casual-lib-version.el

(register-definition-prefixes "casual-lib-version" '("casual-lib-version"))

;;; End of scraped data

(provide 'casual-lib-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; casual-lib-autoloads.el ends here
