;;; ob-restclient-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ob-restclient.el

(autoload 'org-babel-execute:restclient "ob-restclient" "\
Execute a block of Restclient code with org-babel.
This function is called by `org-babel-execute-src-block'

(fn BODY PARAMS)")
(autoload 'org-babel-variable-assignments:restclient "ob-restclient" "\
Return a list of statements assigning variables specified in PARAMS.

(fn PARAMS)")
(register-definition-prefixes "ob-restclient" '("org-babel-"))

;;; End of scraped data

(provide 'ob-restclient-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ob-restclient-autoloads.el ends here
