;;; jarchive-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from jarchive.el

(autoload 'jarchive-patch-eglot "jarchive" "\
This should no longer be used.
Recent versions of Eglot take care of this." t)
(defvar jarchive-mode nil "\
Non-nil if Jarchive mode is enabled.
See the `jarchive-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `jarchive-mode'.")
(custom-autoload 'jarchive-mode "jarchive" nil)
(autoload 'jarchive-mode "jarchive" "\
Teach Emacs to work with jar URIs.

Opening a jar URI via Emacs functions like `find-file' will
automatically extract the contents of a file contained in the jar
and open them in a buffer.

This is a global minor mode.  If called interactively, toggle the
`Jarchive mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='jarchive-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(define-obsolete-function-alias 'jarchive-setup 'jarchive-mode "0.11.0" "Obsolete. Set up Jarchive to open jar URIs.")
(register-definition-prefixes "jarchive" '("jarchive--"))

;;; End of scraped data

(provide 'jarchive-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jarchive-autoloads.el ends here
